name: client-debug
on:
  push:
    branches:
      - fe-dev

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      # 환경변수 확인을 위한 단계 추가
      - name: Debug Environment Variables
        run: echo "REACT_APP_KAKAO_MAPS_APP_KEY BEFORE=${{ secrets.REACT_APP_KAKAO_MAPS_APP_KEY }}"

      # 환경 변수 설정
      - name: Set Environment Variables to .env
        run: echo "REACT_APP_KAKAO_MAPS_APP_KEY=${{ secrets.REACT_APP_KAKAO_MAPS_APP_KEY }}" > ./client/.env

      # 환경변수 확인을 위한 단계 추가
      - name: Debug .env File
        run: cat ./client/.env

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client

      - name: SHOW AWS CLI VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: aws --version

      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://bbangorder \
            --delete
        working-directory: ./client
